import { Lang } from "./translations";

export const termsContent = {
  EN: {
    title: "Terms & Conditions",
    lastUpdated: "Last updated: March 19, 2026",
    sections: [
      {
        title: "1. General",
        content: "These terms and conditions apply to all services provided by Gradient and to all use of our website. By accessing our website or using our services, you agree to be bound by these terms."
      },
      {
        title: "2. Services",
        content: "Gradient provides AI automation, consulting, and implementation services. Each specific project or engagement will be governed by a separate written agreement or statement of work detailing the scope, deliverables, and specific terms."
      },
      {
        title: "3. Pricing and Payment",
        content: "All prices quoted exclude VAT and other applicable taxes unless stated otherwise. Payment deadlines are specified in our invoices. Late payments may lead to the application of interest and the suspension of services."
      },
      {
        title: "4. Intellectual Property",
        content: "All AI systems, proprietary algorithms, workflows, and methodologies developed or used by Gradient remain the exclusive property of Gradient. Clients are granted limited, non-exclusive usage rights for the duration and purpose specified in their project agreement."
      },
      {
        title: "5. Liability",
        content: "Gradient shall not be liable for any indirect, incidental, or consequential damages. Our liability is strictly limited to cases of gross negligence or intentional misconduct, and in any event, capped at the total amount paid by the client for the specific service in question."
      },
      {
        title: "6. Confidentiality",
        content: "Both Gradient and the Client agree to maintain the strict confidentiality of all proprietary or sensitive information shared during the course of our professional relationship."
      },
      {
        title: "7. Use of AI",
        content: "The Client acknowledges that AI technologies are not error-free. All outputs and automated decisions generated by our systems require human validation. Gradient does not guarantee specific business results or absolute accuracy of AI-generated content."
      },
      {
        title: "8. Changes",
        content: "Gradient reserves the right to update or modify these Terms & Conditions at any time. The latest version will always be available on our website."
      },
      {
        title: "9. Governing Law",
        content: "These terms are governed by and construed in accordance with Belgian law. Any disputes arising from these terms or our services shall be subject to the exclusive jurisdiction of the Belgian courts."
      },
      {
        title: "10. Contact",
        content: "Gradient\nAvenue Louise 54\n1050 Brussels, Belgium\nEmail: hello@gradient.be\nPhone: +32 2 543 21 00"
      }
    ]
  },
  NL: {
    title: "Algemene Voorwaarden",
    lastUpdated: "Laatst bijgewerkt: 19 maart 2026",
    sections: [
      {
        title: "1. Algemeen",
        content: "Deze algemene voorwaarden zijn van toepassing op alle diensten geleverd door Gradient en op al het gebruik van onze website. Door onze website te bezoeken of onze diensten te gebruiken, gaat u ermee akkoord gebonden te zijn aan deze voorwaarden."
      },
      {
        title: "2. Diensten",
        content: "Gradient levert AI-automatisering, consultancy en implementatiediensten. Elk specifiek project of elke opdracht wordt beheerst door een afzonderlijke schriftelijke overeenkomst of een werkomschrijving waarin de reikwijdte, de resultaten en de specifieke voorwaarden worden beschreven."
      },
      {
        title: "3. Prijs en Betaling",
        content: "Alle opgegeven prijzen zijn exclusief BTW en andere toepasselijke belastingen, tenzij anders vermeld. Betalingstermijnen worden gespecificeerd in onze facturen. Te late betalingen kunnen leiden tot het aanrekenen van rente en de opschorting van de dienstverlening."
      },
      {
        title: "4. Intellectueel Eigendom",
        content: "Alle AI-systemen, eigen algoritmen, workflows en methodologieën die door Gradient zijn ontwikkeld of worden gebruikt, blijven het exclusieve eigendom van Gradient. Klanten krijgen beperkte, niet-exclusieve gebruiksrechten voor de duur en het doel gespecificeerd in hun projectovereenkomst."
      },
      {
        title: "5. Aansprakelijkheid",
        content: "Gradient is niet aansprakelijk voor enige indirecte, incidentele of gevolgschade. Onze aansprakelijkheid is strikt beperkt tot gevallen van grove nalatigheid of opzettelijk wangedrag, en is in elk geval beperkt tot het totale bedrag dat door de klant is betaald voor de betreffende dienst."
      },
      {
        title: "6. Vertrouwelijkheid",
        content: "Zowel Gradient als de Klant komen overeen om strikte vertrouwelijkheid te betrachten met betrekking tot alle eigen of gevoelige informatie die wordt gedeeld tijdens onze professionele relatie."
      },
      {
        title: "7. Gebruik van AI",
        content: "De Klant erkent dat AI-technologieën niet foutloos zijn. Alle output en geautomatiseerde beslissingen gegenereerd door onze systemen vereisen menselijke validatie. Gradient garandeert geen specifieke bedrijfsresultaten of absolute nauwkeurigheid van door AI gegenereerde inhoud."
      },
      {
        title: "8. Wijzigingen",
        content: "Gradient behoudt zich het recht voor om deze Algemene Voorwaarden op elk moment bij te werken of te wijzigen. De laatste versie zal altijd beschikbaar zijn op onze website."
      },
      {
        title: "9. Toepasselijk Recht",
        content: "Deze voorwaarden worden beheerst door en geïnterpreteerd in overeenstemming met het Belgisch recht. Alle geschillen die voortvloeien uit deze voorwaarden of onze diensten zijn onderworpen aan de exclusieve bevoegdheid van de Belgische rechtbanken."
      },
      {
        title: "10. Contact",
        content: "Gradient\nLouizalaan 54\n1050 Brussel, België\nE-mail: hello@gradient.be\nTelefoon: +32 2 543 21 00"
      }
    ]
  },
  FR: {
    title: "Conditions Générales",
    lastUpdated: "Dernière mise à jour : 19 mars 2026",
    sections: [
      {
        title: "1. Généralités",
        content: "Ces conditions générales s'appliquent à tous les services fournis par Gradient et à toute utilisation de notre site web. En accédant à notre site web ou en utilisant nos services, vous acceptez d'être lié par ces conditions."
      },
      {
        title: "2. Services",
        content: "Gradient fournit des services d'automatisation de l'IA, de conseil et de mise en œuvre. Chaque projet ou mission spécifique sera régi par un accord écrit distinct ou un énoncé des travaux détaillant la portée, les livrables et les conditions spécifiques."
      },
      {
        title: "3. Prix et Paiement",
        content: "Tous les prix indiqués s'entendent hors TVA et autres taxes applicables, sauf indication contraire. Les délais de paiement sont précisés dans nos factures. Les retards de paiement peuvent entraîner l'application d'intérêts et la suspension des services."
      },
      {
        title: "4. Propriété Intellectuelle",
        content: "Tous les systèmes d'IA, algorithmes propriétaires, flux de travail et méthodologies développés ou utilisés par Gradient restent la propriété exclusive de Gradient. Les clients bénéficient de droits d'utilisation limités et non exclusifs pour la durée et l'objectif spécifiés dans leur accord de projet."
      },
      {
        title: "5. Responsabilité",
        content: "Gradient ne peut être tenu responsable des dommages indirects, accessoires ou consécutifs. Notre responsabilité est strictement limitée aux cas de négligence grave ou de faute intentionnelle, et en tout état de cause, plafonnée au montant total payé par le client pour le service spécifique en question."
      },
      {
        title: "6. Confidentialité",
        content: "Gradient et le Client acceptent de maintenir la stricte confidentialité de toutes les informations propriétaires ou sensibles partagées au cours de leur relation professionnelle."
      },
      {
        title: "7. Utilisation de l'IA",
        content: "Le Client reconnaît que les technologies d'IA ne sont pas sans erreur. Tous les résultats et décisions automatisées générés par nos systèmes nécessitent une validation humaine. Gradient ne garantit pas de résultats commerciaux spécifiques ni l'exactitude absolue du contenu généré par l'IA."
      },
      {
        title: "8. Modifications",
        content: "Gradient se réserve le droit de mettre à jour ou de modifier ces Conditions Générales à tout moment. La dernière version sera toujours disponible sur notre site web."
      },
      {
        title: "9. Droit Applicable",
        content: "Ces conditions sont régies et interprétées conformément au droit belge. Tout litige découlant de ces conditions ou de nos services sera soumis à la juridiction exclusive des tribunaux belges."
      },
      {
        title: "10. Contact",
        content: "Gradient\nAvenue Louise 54\n1050 Bruxelles, Belgique\nEmail : hello@gradient.be\nTéléphone : +32 2 543 21 00"
      }
    ]
  }
};
